### ISSUE TITLE
Creating a Dev Branch

### ISSUE THREAD

**Issue by mraza007** [CUNYSuite/CunyFirstAPI#21]
I think we need to keep production and development separate. So we can push changes to the dev branch and later merge them to the master branch if necessary

**Comment by Huddie** [comment]
Ya! We actually plan to have 2 branches

- master
- prod

master is where things get merged via PR and prod is where things get merged into when it's time for a new release

**Comment by mraza007** [comment]
Yup it just makes stuff easier :+1:
